services:
  api01: &api
    # image: ryanjorgeac/rinha-backend-2024-q1-fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    network_mode: host
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=rinha
      - DB_USER=rinha
      - DB_PW=rinha
      - DB_PORT=5432
      - POOL_SIZE=100
      - PORT=8081
      - MAX_WORKERS=2
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "120MB"

  api02:
    <<: *api
    hostname: api02
    network_mode: host
    environment:
      - DB_HOST=127.0.0.1
      - DB_NAME=rinha
      - DB_USER=rinha
      - DB_PW=rinha
      - DB_PORT=5432
      - POOL_SIZE=100
      - PORT=8082
      - MAX_WORKERS=2
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:1.25.3
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
      image: postgres:16.2
      hostname: db
      network_mode: host
      command: 'postgres -c log_min_error_statement=panic -c log_min_duration_statement=-1 -c log_min_duration_sample=-1 -c log_min_messages=panic  -c checkpoint_timeout=600 -c max_wal_size=4096 -c max_connections=400 -c shared_buffers=175MB -c effective_io_concurrency=4 -c synchronous_commit=off'
      environment:
        - POSTGRES_PASSWORD=rinha
        - POSTGRES_USER=rinha
        - POSTGRES_DB=rinha
        - PGDATA=/var/lib/postgresql/data/rinha
      ports:
        - "5432:5432"
      volumes:
        - ./sql/init_db.sql:/docker-entrypoint-initdb.d/script.sql
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U rinha -d rinha -p 5432"]
        interval: 5s
        timeout: 5s
        retries: 20
        start_period: 10s
      deploy:
        resources:
          limits:
            cpus: "0.55"
            memory: "300MB"